[package]
name = "lnx"
version = "0.6.0"
authors = ["Harrison Burt <57491488+ChillFish8@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "rt", "signal"] }
hyper = { version = "0.14", features = ["server", "http1", "http2"] }
fern = { version = "0.6", features = ["colored"] }
tower-http = { version = "0.1", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
hashbrown = { version = "0.11", features = ["serde"] }
axum = "0.2.8"
sqlx = { version = "0.5", features = ["sqlite", "runtime-tokio-rustls"] }
tower = "0.4"
structopt = "0.3"
tokio-rustls = "0.22"
log = "0.4"
anyhow = "1"
chrono = "0.4"
num_cpus = "1.13"
bytes = "1"
serde_json = "1"
headers = "0.3.4"
evmap = "10"
parking_lot = "0.11"
rand = "0.8.4"

engine = { path = "./search-engine/engine" }

[profile.release]
lto = "fat"
codegen-units = 1