[workspace]
members = [
    "lnx",
    "lnx-common",
    "lnx-indexer",
    "lnx-cluster",
    "lnx-storage",
    "lnx-executor",
    "lnx-io",

]

[workspace.dependencies]
arc-swap = "1.6.0"
anyhow = "1"
bytecheck = "0.6.10"
bytes = "1"
crc32fast = "1.3.2"
crossbeam = "0.8.2"
cityhash-sys = "=1.0.2" # Newer versions require nightly
flume = "0.10.14"
futures = "0.3.26"
serde_json = "1"
smallvec = "1.10.0"
num_cpus = "1.15"
parse-size = "1.0"
parking_lot = "0.12.1"
humansize = "2.1"
humantime = "2.1"
hashbrown = "0.13"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.3.16"
thiserror = "1"
tantivy = "0.19"
uuid = "1"
rayon = "1.6.1"
once_cell = "1.17.1"
memmap2 = "0.5.10"
zstd = "0.12.3+zstd.1.5.2"
exponential-backoff = "1.2.0"

datacake = { version = "0.6.0", default-features = false, features = ["datacake-crdt", "datacake-rpc", "datacake-eventual-consistency", "datacake-node"] }
datacake-lmdb = "0.1.0"

puppet = { version = "0.4.0", default-features = false }
validator = { version = "0.16", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
rkyv = { version = "0.7", features = ["validation"] }
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14.25", features = ["full"] }

jocky = { git = "https://github.com/ChillFish8/jocky.git", rev = "c989fce" }
test-helper = { git = "https://github.com/lnx-search/datacake.git", rev = "c968fd4" }