[package]
name = "lnx-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lnx-utils = { path = "../lnx-utils" }

serde = { version = "1", features = ["derive"] }
hashbrown = { version = "0.12.0", features = ["serde"] }
tantivy = { git = "https://github.com/quickwit-oss/tantivy.git", rev = "cef1457" }

serde_json = "1.0.78"
uuid = "0.8.2"
bincode = "2.0.0-beta.3"
base64 = "0.13.0"
thiserror = "1.0.30"
deunicode = "1.3.1"
crc32fast = "1.3.2"
anyhow = "1"

[dev-dependencies]
serde_json = "1.0.78"
anyhow = "1.0.53"