[package]
name = "lnx-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }

base64 = "0.13.0"
thiserror = "1.0.30"
tantivy = "0.16.1"
deunicode = "1.3.1"
