[package]
name = "lnx-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lnx-common = { path = "../lnx-common" }
lnx-utils = { path = "../lnx-utils" }

serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8.1", features = ["v4"] }
hashbrown = { version = "0.12.0", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
sled = { version = "0.34.7", features = ["compression"] }

bincode = "2.0.0-beta.3"
scylla = "0.4.1"
parking_lot = "0.12"
arc-swap = "1.5.0"
once_cell = "1.9.0"
itertools = "0.10.3"
futures-util = "0.3.21"
anyhow = "1"
thiserror = "1.0.30"
async-trait = "0.1.52"
tracing = "0.1.30"
tracing-futures = "0.2.5"