[package]
name = "lnx-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lnx-common = { path = "../lnx-common" }
lnx-utils = { path = "../lnx-utils" }

sled = "0.34.7"
anyhow = "1"
scylla = "0.4.1"
chrono = "0.4.19"
async-trait = "0.1.52"
serde_json = "1.0.79"
parking_lot = "0.12.0"
tracing = "0.1.30"
tracing-futures = "0.2.5"
hashbrown = "0.12.0"

serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }  # todo change