[package]
name = "scylladb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lnx-storage = { path = "../../lnx-storage" }
lnx-common = { path = "../../lnx-common" }

serde = { version = "1", features = ["derive"] }
hashbrown = { version = "0.12.0", features = ["serde"] }

anyhow = "1"
thiserror = "1.0.30"
once_cell = "1.9.0"
serde_json = "1"
scylla = "0.4.1"
tracing = "0.1.31"
tracing-futures = "0.2.5"