[package]
name = "lnx-schema"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lnx-tools = { path = "../lnx-tools" }

tantivy = { workspace = true }
hashbrown = { workspace = true }